"""s

Revision ID: 092bdc4763f4
Revises: 3852441e2b88
Create Date: 2021-11-19 14:52:19.680987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '092bdc4763f4'
down_revision = '3852441e2b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'name',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'name',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
