"""phone length

Revision ID: 13fb71da77a4
Revises: fe9b24b961a2
Create Date: 2021-11-19 12:23:20.998325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13fb71da77a4'
down_revision = 'fe9b24b961a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_', sa.String(length=100), nullable=False))
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', mysql.VARCHAR(length=12), nullable=False))
    op.drop_column('user', 'phone_')
    # ### end Alembic commands ###
