"""image length

Revision ID: 28591b5d79fc
Revises: fca75a4b0a5f
Create Date: 2021-11-20 05:19:50.048891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28591b5d79fc'
down_revision = 'fca75a4b0a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image_file_', sa.String(length=255), nullable=False))
    op.drop_column('item', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image_file', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('item', 'image_file_')
    # ### end Alembic commands ###
