"""sold

Revision ID: 4b4d04724e66
Revises: 5328496cb186
Create Date: 2021-11-19 15:13:39.839121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b4d04724e66'
down_revision = '5328496cb186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('sold', sa.Boolean(), nullable=False))
    op.drop_column('item', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('price', mysql.FLOAT(), nullable=False))
    op.drop_column('item', 'sold')
    # ### end Alembic commands ###
