"""price

Revision ID: 5328496cb186
Revises: 677a22201298
Create Date: 2021-11-19 15:11:32.517900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5328496cb186'
down_revision = '677a22201298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'price')
    # ### end Alembic commands ###
