"""s

Revision ID: 59377405fc36
Revises: 092bdc4763f4
Create Date: 2021-11-19 14:55:12.121773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59377405fc36'
down_revision = '092bdc4763f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name_', sa.String(length=250), nullable=False))
    op.drop_column('item', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('item', 'name_')
    # ### end Alembic commands ###
