"""user

Revision ID: 6d0046e0c064
Revises: 11b2b462fbc0
Create Date: 2021-11-19 17:26:05.862906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d0046e0c064'
down_revision = '11b2b462fbc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name', sa.String(length=250), nullable=False))
    op.add_column('item', sa.Column('user', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'item', 'user', ['user'], ['id'])
    op.drop_column('item', 'sds')
    op.drop_column('item', 'name_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name_', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('item', sa.Column('sds', mysql.VARCHAR(length=250), nullable=False))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'user')
    op.drop_column('item', 'name')
    # ### end Alembic commands ###
