"""user

Revision ID: bf319bb4350d
Revises: 4b4d04724e66
Create Date: 2021-11-19 17:12:05.353126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf319bb4350d'
down_revision = '4b4d04724e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name_', sa.String(length=250), nullable=False))
    op.drop_column('item', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('item', 'name_')
    # ### end Alembic commands ###
