"""bid

Revision ID: fca75a4b0a5f
Revises: 6d0046e0c064
Create Date: 2021-11-19 18:22:52.883256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca75a4b0a5f'
down_revision = '6d0046e0c064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid', sa.Column('item', sa.Integer(), nullable=False))
    op.add_column('bid', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('bid', sa.Column('user', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bid', 'user', ['user'], ['id'])
    op.create_foreign_key(None, 'bid', 'item', ['item'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bid', type_='foreignkey')
    op.drop_constraint(None, 'bid', type_='foreignkey')
    op.drop_column('bid', 'user')
    op.drop_column('bid', 'price')
    op.drop_column('bid', 'item')
    # ### end Alembic commands ###
