"""phone

Revision ID: fe9b24b961a2
Revises: 75e8063fb38d
Create Date: 2021-11-19 12:20:03.976124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe9b24b961a2'
down_revision = '75e8063fb38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_index('phone', table_name='user')
    op.drop_column('user', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_file', mysql.VARCHAR(length=20), nullable=False))
    op.create_index('phone', 'user', ['phone'], unique=True)
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
